name: Kubernetes CI

on:
  push:
    branches:
      - production

permissions:
  contents: write

jobs:
  webapp-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get Latest Tag
        id: tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)

          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            version=${latest_tag#v}
            IFS='.' read -r major minor patch <<< "$version"
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
          fi

          echo "NEW_TAG=$new_tag" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git tag ${{ steps.tag.outputs.NEW_TAG }}
          git push origin ${{ steps.tag.outputs.NEW_TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t sumonaust/webapp:${{ steps.tag.outputs.NEW_TAG }} .

      - name: Push Docker Image
        run: |
          docker push sumonaust/webapp:${{ steps.tag.outputs.NEW_TAG }}

      - name: Push Latest Tag
        run: |
          docker tag sumonaust/webapp:${{ steps.tag.outputs.NEW_TAG }} sumonaust/webapp:latest
          docker push sumonaust/webapp:latest